name: build-with-cli
on: [push, workflow_dispatch]

permissions:
  id-token: write # This is required for requesting the JWT
  packages: write # This is required to push to GitHub registry
jobs:
  build_with_docker:
    runs-on: ubuntu-latest
    name: Build with Docker
    env:
      IMAGE_NAME: docker-django-example
      IMAGE_REPO: ghcr.io/${{ github.repository_owner }}
      VERSION: v0.0.1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # We are going to push to GH Container Registry
      - name: Log in to GitHub registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      # Run Docker build with Buildkit driver
      - name: Docker Build and Push
        run: |
          DOCKER_BUILDKIT=1 docker build . --tag $IMAGE_NAME
          docker tag $IMAGE_NAME $IMAGE_REPO/$IMAGE_NAME:$VERSION
          docker push $IMAGE_REPO/$IMAGE_NAME:$VERSION

  build_with_nscloud:
    runs-on: ubuntu-latest
    name: Build with Namespace Cloud
    env:
      IMAGE_NAME: nsc-django-example
      IMAGE_REPO: ghcr.io/${{ github.repository_owner }}
      VERSION: v0.0.1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # We are going to push to GH Container Registry
      - name: Log in to GitHub registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      # Install CLI and authenticate to Namespace Cloud
      - name: Install and configure Namespace Cloud CLI
        uses: namespacelabs/nscloud-setup@v0.0.4

      # Build and push with your Namespace Cloud workspace build cluster
      - name: Build and push with Namespace Cloud cluster
        run: |
          nsc build . -t $IMAGE_REPO/$IMAGE_NAME:$VERSION --push
